// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-funding-opportunities.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supa(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_funding_opportunities_default = defineTool({
  name: "list_funding_opportunities",
  title: "List funding opportunities",
  description: "List active funding opportunities on NGO Bridge. Optionally filter by sector, country, or search text in title/summary.",
  inputSchema: {
    sector: z.string().optional().describe("Filter by sector (e.g. 'WASH', 'Agriculture', 'Health')."),
    country: z.string().optional().describe("Filter by eligible country (ISO name)."),
    search: z.string().optional().describe("Free-text search over title and summary."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sector, country, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supa(ctx).from("funding_opportunities").select("id, funder, title, summary, sectors, countries, sdgs, min_amount, max_amount, currency, deadline, url").eq("is_active", true).limit(limit ?? 20);
    if (sector) q = q.contains("sectors", [sector]);
    if (country) q = q.contains("countries", [country]);
    if (search) q = q.or(`title.ilike.%${search}%,summary.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { opportunities: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-my-organizations.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supa2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_organizations_default = defineTool2({
  name: "list_my_organizations",
  title: "List my organizations",
  description: "List organizations owned by the signed-in user on NGO Bridge.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supa2(ctx).from("organizations").select("id, name, mission, sector, country, stage, funding_required, sdgs, beneficiary_type, readiness_score, is_verified").eq("owner_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { organizations: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-funding-matches.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supa3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_funding_matches_default = defineTool3({
  name: "list_funding_matches",
  title: "List funding matches for an organization",
  description: "List AI-computed funding opportunity matches (score, reasons, gaps) for one of the signed-in user's organizations.",
  inputSchema: {
    organization_id: z2.string().uuid().describe("The organization ID (must belong to the signed-in user)."),
    min_score: z2.number().int().min(0).max(100).optional().describe("Only return matches at or above this score.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ organization_id, min_score }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supa3(ctx).from("funding_matches").select("score, reasons, gaps, computed_at, funding_opportunities(id, funder, title, summary, deadline, url, min_amount, max_amount, currency)").eq("organization_id", organization_id).order("score", { ascending: false });
    if (min_score !== void 0) q = q.gte("score", min_score);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { matches: data ?? [] } };
  }
});

// src/lib/mcp/tools/discover-funders.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supa4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var discover_funders_default = defineTool4({
  name: "run_funding_discovery",
  title: "Run AI funding discovery",
  description: "Trigger the AI Funding Intelligence engine to recompute funder matches for one of the user's organizations. Returns match scores, reasons, and gaps.",
  inputSchema: {
    organization_id: z3.string().uuid().describe("The organization to score against active funding opportunities.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: true },
  handler: async ({ organization_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = supa4(ctx);
    const { data: org, error: orgErr } = await client.from("organizations").select("id, owner_id").eq("id", organization_id).maybeSingle();
    if (orgErr || !org || org.owner_id !== ctx.getUserId()) {
      return { content: [{ type: "text", text: "Organization not found or not owned by this user." }], isError: true };
    }
    const { data, error } = await client.functions.invoke("ai-discover-funders", { body: { organization_id } });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: data };
  }
});

// src/lib/mcp/tools/search-organizations.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
function supa5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_organizations_default = defineTool5({
  name: "search_organizations",
  title: "Search organizations",
  description: "Search public/verified organizations on NGO Bridge by name, sector, or country.",
  inputSchema: {
    search: z4.string().optional().describe("Free-text search over name and mission."),
    sector: z4.string().optional(),
    country: z4.string().optional(),
    limit: z4.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, sector, country, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supa5(ctx).from("organizations").select("id, name, mission, sector, country, stage, sdgs, funding_required, readiness_score, is_verified").limit(limit ?? 20);
    if (sector) q = q.eq("sector", sector);
    if (country) q = q.eq("country", country);
    if (search) q = q.or(`name.ilike.%${search}%,mission.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { organizations: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iaugaafivggkadlojoqu";
var mcp_default = defineMcp({
  name: "ngo-bridge-mcp",
  title: "NGO Bridge",
  version: "0.1.0",
  instructions: "Tools for NGO Bridge \u2014 a platform connecting African NGOs and startups with investors and funding opportunities. Use `search_organizations` and `list_funding_opportunities` to explore the public catalog, `list_my_organizations` to see the signed-in user's organizations, `list_funding_matches` to view AI-scored funder matches for one of their organizations, and `run_funding_discovery` to recompute matches.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_organizations_default,
    list_funding_opportunities_default,
    list_my_organizations_default,
    list_funding_matches_default,
    discover_funders_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
